### ISSUE TITLE
Идея контроля списка модов

### ISSUE THREAD

**Issue by jkulvich** [mncred/discuss#2]

**Comment by jkulvich** [comment]
```yaml
$schema: http://...
api: mncplay/v1
servers:
  "MNC.RED :: Stone":
    autoconnect: true
    resourcepacks:
      - url: ...
    client:
      bundle:
        url: http://...
        md5: ...
    server:
      bundle: ...
```
